# Factor Analysis: Theoretical Models

\emph{Factor Analysis} is a statistical technique that is widely used in applied fields to identify hidden patterns or latent structures behind large sets of observed variables. The goal is to reduce complexity by grouping related variables into a smaller number of underlying \emph{factors}, which are easier to interpret.

Some areas where factor analysis is commonly applied include:
\begin{itemize}
    \item \textbf{Psychology and social sciences:} to uncover latent traits such as intelligence, anxiety, personality dimensions, or satisfaction levels, based on responses to questionnaires or surveys.
    \item \textbf{Marketing and consumer research:} to identify purchasing motives, brand perceptions, or market segments from customer behavior data.
    \item \textbf{Finance and economics:} to reveal hidden drivers of stock returns, macroeconomic indicators, or risk factors.
    \item \textbf{Education:} to analyze test items and determine whether they measure common skills or abilities.
    \item \textbf{Biological and health sciences:} to find latent structures in genetic data, symptom checklists, or patient-reported outcomes.
\end{itemize}

In practice, Factor Analysis is used when researchers suspect that a few unobserved dimensions are responsible for the correlations among many observed variables. It is especially useful for building measurement scales, data reduction, and gaining insights into the structure of complex datasets.


## Factor Analysis Setting

The theoretical context for factor analysis is a relation of the form 
$$
X = \mu + LF + \epsilon 
$$
where:
\begin{itemize}
    \item $X$ is a random vector of $p$ observed variables (indicators).
    \item $\mu$ is a constant vector of dimension $p$.
    \item $L$ is a $p \times m$ constant matrix known as the matrix of \emph{factor loadings.}
    \item $F \sim \N(0,I_{m})$ is a vector of $m$ latent factors (unobserved variables) that are assumed to be normally distributed with mean zero and identity covariance matrix.
    \item $\epsilon \sim \N(0,\Psi)$ is a vector of unique errors (specific variances) that are also assumed to be normally distributed with mean zero and diagonal covariance matrix $\Psi = \diag(\sigma_{1}^{2}, \ldots, \sigma_{p}^{2})$.
    \item The factors $F$ and the errors $\epsilon$ are assumed to be independent, in particular $\Cov[F,\epsilon] = 0$.
\end{itemize}

As a consequence of these assumptions, we have that 
$$
\E[X] = \E[\mu + LF + \epsilon] = \E[\mu] + L\E[F] + \E[\epsilon] = \mu 
$$
and 
\begin{align*}
\Var[X] & = \Var[LF + \epsilon] \\
 & = \E[(LF + \epsilon)(LF + \epsilon)^{T}] \\
 & = \E[LF F^{T}L^{T}] + \E[\epsilon \epsilon^{T}] + \E[LF \epsilon^{T}] + \E[\epsilon F^{T}L^{T}] \\
  & = L \E[FF^{T}] L^{T} + \E[\epsilon \epsilon^{T}] + L \E[F \epsilon^{T}] + \E[\epsilon F^{T}] L^{T} \\
  & = L I_{m} L^{T} + \Psi + L 0 + 0 L^{T} \\
  & = LL^{T} + \Psi 
\end{align*}
Furthermore, since $X$ is a linear combination of normally distributed variables, it follows that 
$$
X \sim \N(\mu, LL^{T} + \Psi)
$$

## Variance Decomposition 
The variance decomposition $\Var[X] = LL^{T} + \Psi$ shows that the total variance of the observed variables $X$ can be decomposed into two components:
\begin{itemize}
    \item \textbf{Common variance ($LL^{T}$):} This part of the variance is explained by the common factors $F$. It captures the shared variability among the observed variables that can be attributed to the underlying latent structure.
    \item \textbf{Unique variance ($\Psi$):} This part of the variance is specific to each observed variable and is not explained by the common factors. It includes measurement errors and any other variability that is unique to each variable. 
\end{itemize}
In particular, the variance of each individual observed variable $X_{i}$ can be expressed as 
$$ 
\Var[X_{i}] = \sum_{j=1}^{m} L_{ij}^{2} + \sigma_{i}^{2} 
$$
where $h_{i}^{2} = \sum_{j=1}^{m} L_{ij}^{2}$ is called the \emph{communality} of the variable $X_{i}$, representing the portion of its variance explained by the common factors, and $\sigma_{i}^{2}$ is the unique variance specific to $X_{i}$.

## Factor Score Estimation 

Assume that we have a model 
$$
X = \mu + LF + \epsilon 
$$
with the same conditions as before. Then the joint distribution of $X$ and $F$ is given by 
$$ 
\begin{bmatrix} 
X \\ F 
\end{bmatrix} \sim \N \left( 
\begin{bmatrix} 
\mu \\ 0 
\end{bmatrix},
\begin{bmatrix} 
LL^{T} + \Psi & L \\ 
L^{T} & I_{m} 
\end{bmatrix} 
\right) 
$$
Notice that, in particular,
$$
\Cov[X,F] = \E[(X - \mu)(F - 0)^{T}] = \E[(LF + \epsilon)F^{T}] = L \E[FF^{T}] + \E[\epsilon F^{T}] = L I_{m} + 0 = L 
$$
Using the properties of the multivariate normal distribution, we can derive the conditional distribution of the factors $F$ given the observed variables $X$. This conditional distribution is also normal, with mean and covariance given by 
$$ 
[F | X = x] \sim \N \left( L^{T}(LL^{T} + \Psi)^{-1}(x - \mu), I_{m} - L^{T}(LL^{T} + \Psi)^{-1}L \right) 
$$ 
The mean of this conditional distribution, 
$$ 
\E[F | X = x] = L^{T}(LL^{T} + \Psi)^{-1}(x - \mu) 
$$ 
is known as the \emph{factor score} for the observed data point $X = x$. It provides an estimate of the latent factors based on the observed variables and the factor loadings. The covariance matrix 
$$
I_{m} - L^{T}(LL^{T} + \Psi)^{-1}L 
$$ 
represents the uncertainty associated with the factor score estimates. 

\begin{remark} 
Notice that, if 
$$
f = \E[F | X = x] = L^{T}(LL^{T} + \Psi)^{-1}(x - \mu)
$$
then, in general, the \emph{residual}
$$ 
r(x) = x - \mu - Lf 
$$ 
is different from zero. In fact, as a function of the random variable $X$, the residual has probability distribution 
$$
r(X) \sim \N\Bigg(0, L \left(I_m + L^T \Psi^{-1} L \right)^{-1} L^T + \Psi \Bigg)
$$

\end{remark}

## Rotation of Factors 

An important aspect of factor analysis is that the factors are not uniquely defined. If $F$ is a vector of factors, then any orthogonal transformation $F^{*} = QF$, where $Q$ is an orthogonal matrix (i.e., $Q^{T}Q = I$), will yield a new set of factors that explain the same variance in the observed variables. In particular, 
$$
\Var[F^{*}] = \Var[QF] = Q \Var[F] Q^{T} = Q I_{m} Q^{T} = I_{m} 
$$ 
The corresponding factor loadings will be transformed as $L^{*} = LQ^{T}$. In other words, if 
$$
X = \mu + LF + \epsilon
$$
is a valid factor model, then so is 
$$ 
X = \mu + L^{*}F^{*} + \epsilon = \mu + LQ^{T}QF + \epsilon = \mu + LF + \epsilon
$$ 
This means that the solution to a factor analysis problem is not unique, and different rotations of the factors can lead to different interpretations. In the next chapter, we will explore various practical methods for factor analysis and rotation techniques geared towards achieving more interpretable factor solutions.
